package jp.gr.java_conf.ka_ka_xyz.exception;

public class MMDARException extends RuntimeException{

	
	/**
	 * generated by eclipse.
	 */
	private static final long serialVersionUID = -8910155108186789677L;

	public MMDARException(){
		super();
	}
	
	public MMDARException(String msg){
		super(msg);
	}
	
	public MMDARException(Throwable t){
		super(t);
	}

	public MMDARException(String msg, Throwable t){
		super(msg, t);
	}

}
