package jp.gr.java_conf.ka_ka_xyz.exception;

public class TooHugeFileException extends MMDARException{

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 1464226073179072824L;

	public TooHugeFileException(){
		super();
	}
	
	public TooHugeFileException(String msg){
		super(msg);
	}
	
	public TooHugeFileException(Throwable t){
		super(t);
	}

	public TooHugeFileException(String msg, Throwable t){
		super(msg, t);
	}
}
